CREATE TABLE APPROVAL_ITEM 
(
	BOARD_ID      	 INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '글번호',
	TITLE            VARCHAR(700) COMMENT '제목',
	USERID    		 INT COMMENT '작성자 ID',
	NAME             VARCHAR(200) COMMENT '작성자이름',
	APPROVAL_USERID  INT COMMENT '결재자 ID',
	APPROVAL_NAME    VARCHAR(200) COMMENT '결재자 이름',
	CONTENT          VARCHAR(2000) COMMENT '내용',
	STATUS           SMALLINT DEFAULT 0 NOT NULL COMMENT '상태',
	ISVISB           TINYINT DEFAULT 0 NOT NULL COMMENT '보임여부',
	RGST_DATE        DATETIME DEFAULT current_timestamp() COMMENT '등록일시',
	LAST_UPDT 		 DATETIME COMMENT '결재완료일시'	
) COMMENT = '결재 게시판';


CREATE table HR_USER
(
  USER_ID           INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '작성자 ID',
  USER_NAME         VARCHAR(36) not null  COMMENT '작성자이름',
  ENCRYTED_PASSWORD VARCHAR(128) not null COMMENT '비밀번호',
  ENABLED           BIGINT not null COMMENT '보임여부',
  ROLE_ID   		BIGINT not null COMMENT '롤 번호',
  ROLE_NAME VARCHAR(30) not null COMMENT '롤 이름'
) COMMENT = '사용자';
 
insert into HR_User (USER_NAME, ENCRYTED_PASSWORD, ENABLED, ROLE_ID, ROLE_NAME)
values ('사용자1', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1, 1, 'ROLE_USER');

insert into HR_User (USER_NAME, ENCRYTED_PASSWORD, ENABLED, ROLE_ID, ROLE_NAME)
values ('사용자2', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1, 1, 'ROLE_USER');

insert into HR_User (USER_NAME, ENCRYTED_PASSWORD, ENABLED, ROLE_ID, ROLE_NAME)
values ('사용자3', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1, 1, 'ROLE_USER');
 
 
insert into HR_User (USER_NAME, ENCRYTED_PASSWORD, ENABLED, ROLE_ID, ROLE_NAME)
values ('결재자1', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1 ,2,'ROLE_ADMIN');

insert into HR_User (USER_NAME, ENCRYTED_PASSWORD, ENABLED, ROLE_ID, ROLE_NAME)
values ('결재자2', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1 ,2,'ROLE_ADMIN');

insert into HR_User (USER_NAME, ENCRYTED_PASSWORD, ENABLED, ROLE_ID, ROLE_NAME)
values ('결재자3', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1 ,2,'ROLE_ADMIN');